name: Build and Publish container for new releases

on:
  release:
    types:
      - published


jobs:
  build:
    name:                         Build and push image
    runs-on:                      ubuntu-latest
    steps:

    - uses:                       actions/checkout@v2

    - name:                       Build Image
      uses:                       redhat-actions/buildah-build@v2
      with:
        image:                    polkadot-runtime-prom-exporter
        tags:                     ${{ github.event.release.tag_name }} latest
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VCS_REF=${{ github.ref }}
          BUILD_DATE=${{ github.event.release.published_at }}

    - name:                       Push image to docker.io
      id:                         push-to-dockerhub
      uses:                       redhat-actions/push-to-registry@v2.1
      with:
        registry:                 docker.io/paritytech
        image:                    polkadot-runtime-prom-exporter
        tags:                     ${{ github.event.release.tag_name }} latest
        username:                 ${{ secrets.DOCKERHUB_USERNAME }}
        password:                 ${{ secrets.DOCKERHUB_TOKEN }}

    - name:                       Check the image
      run: |
        echo "New image has been pushed to ${{ steps.push-to-dockerhub.outputs.registry-path }}"
